# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.19.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        # additional_dependencies:
        # -   eslint@4.15.0
        # -   eslint-config-google@0.7.1
        # -   eslint-loader@1.6.1
        # -   eslint-plugin-react@6.10.3
        # -   babel-eslint@6.1.2
